import path from "node:path";
import { Effect } from "effect";
import { parseJsonRegistry, type RegistryEntry } from "../../domain/registry.js";
import { readTextFile, writeTextFile } from "../../shared/fs-support.js";
import { DocsBuildCommand, DocsBuildResult } from "./request.js";

const docPattern = /{%-?\s*doc\s*-?%}([\s\S]*?){%-?\s*enddoc\s*-?%}/;

type EventsContract = {
  readonly events?: readonly { readonly name?: string; readonly source?: string; readonly detail?: string }[];
};

function firstDocLine(documentation: string | undefined): string {
  if (documentation === undefined) return "";
  return (
    documentation
      .split("\n")
      .map((line) => line.trim())
      .find((line) => line.length > 0 && !line.startsWith("@")) ?? ""
  );
}

async function entrySummary(root: string, entry: RegistryEntry): Promise<string> {
  if (entry.path === undefined || !entry.path.endsWith(".liquid")) return "";
  const content = await readTextFile(path.join(root, entry.path));
  return firstDocLine(docPattern.exec(content ?? "")?.[1]);
}

function location(entry: RegistryEntry): string {
  if (entry.path !== undefined) return `\`${entry.path}\``;
  if (entry.via !== undefined) return `via \`${entry.via}\``;
  return "";
}

export const docsBuildHandler = Effect.fn("docsBuildHandler")(function* (command: DocsBuildCommand) {
  const registryContent = yield* Effect.promise(() => readTextFile(path.join(command.root, command.jsonPath)));
  const entries = registryContent === undefined ? undefined : parseJsonRegistry(registryContent);
  if (entries === undefined) {
    return new DocsBuildResult({
      lines: [`${command.jsonPath} missing or invalid: run \`oio registry sync\``],
      exitCode: 2,
    });
  }

  const lines: string[] = [];

  const catalog: string[] = [
    "# Primitive Catalog",
    "",
    "Generated by `oio docs build` from registry.json and LiquidDoc headers. Do not edit by hand.",
    "",
  ];
  for (const surface of ["merchant", "internal", "preset", "contract"] as const) {
    const surfaceEntries = entries
      .filter((entry) => entry.surface === surface)
      .toSorted((a, b) => a.id.localeCompare(b.id));
    if (surfaceEntries.length === 0) continue;
    catalog.push(`## ${surface[0]?.toUpperCase()}${surface.slice(1)} (${surfaceEntries.length})`, "");
    catalog.push("| ID | Delivery | Status | Location | Summary |", "| --- | --- | --- | --- | --- |");
    for (const entry of surfaceEntries) {
      const summary = yield* Effect.promise(() => entrySummary(command.root, entry));
      catalog.push(
        `| ${entry.id} | ${entry.delivery ?? ""} | ${entry.status} | ${location(entry)} | ${summary.replaceAll("|", "\\|")} |`,
      );
    }
    catalog.push("");
  }
  const catalogPath = path.join(command.root, command.outputDir, "primitives.md");
  yield* Effect.promise(() => writeTextFile(catalogPath, `${catalog.join("\n")}\n`));
  lines.push(`wrote ${command.outputDir}/primitives.md (${entries.length} entries)`);

  if (command.eventsPath !== undefined) {
    const eventsContent = yield* Effect.promise(() => readTextFile(path.join(command.root, command.eventsPath ?? "")));
    if (eventsContent !== undefined) {
      const contract = JSON.parse(eventsContent) as EventsContract;
      const events = ["# Storefront Event Contract", "", "Generated by `oio docs build` from events.json.", ""];
      events.push("| Event | Source | Detail |", "| --- | --- | --- |");
      for (const event of contract.events ?? []) {
        events.push(`| \`${event.name ?? ""}\` | ${event.source ?? ""} | ${event.detail ?? ""} |`);
      }
      yield* Effect.promise(() =>
        writeTextFile(path.join(command.root, command.outputDir, "events.md"), `${events.join("\n")}\n`),
      );
      lines.push(`wrote ${command.outputDir}/events.md`);
    }
  }

  const implemented = entries.filter((entry) => entry.status === "implemented").length;
  const merchant = entries.filter((entry) => entry.surface === "merchant").length;
  const llms = [
    "# llms.txt",
    "",
    "> Shopify theme built on the Theme OS composition system: Liquid-rendered",
    "> primitives, light-DOM Lit enhancers, and XState machines, governed by a",
    "> machine-readable registry and event contract.",
    "",
    `- Primitive registry: ${command.jsonPath} (${entries.length} entries, ${implemented} implemented, ${merchant} merchant-facing)`,
    `- Primitive catalog: ${command.outputDir}/primitives.md`,
    ...(command.eventsPath === undefined ? [] : [`- Event contract: ${command.eventsPath}`]),
    "- Machines: frontend/features/*/*-machine.ts (ids follow oio.<feature>)",
    "- Custom elements: oio-* prefix, light DOM, enhance server-rendered markup",
    "",
  ];
  yield* Effect.promise(() => writeTextFile(path.join(command.root, "llms.txt"), llms.join("\n")));
  lines.push("wrote llms.txt");

  return new DocsBuildResult({ lines, exitCode: 0 });
});
